---
apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization
namespace: tailscale
resources:
  - helmrelease.yaml
  - helmrepository.yaml
  - tailscale-rbac.yaml
  - namespace.yaml
  - tailscale-secret.yaml
  - tailscale-token.yaml
